---

- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "remove dependencies that are no longer required"
  become: yes
  apt:
    autoremove: yes

- name: "install nodejs and npm"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install n"
  become: yes
  npm:
    name: n
    global: yes
    production: yes

- name: "install nodejs 13.8.0"
  become: yes
  shell: n 13.8.0

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Create directory
  become: yes
  file:
    path: "/project/udaapp"
    state: directory
    mode: 0644

- name: copy operation
  tags: checksum
  block:
    - name: Checksum of original file
      stat:
        path: files/artifact.tar.gz
        checksum_algorithm: sha1
      register: src_info

- name: Upload artifact
  copy:
    src: files/artifact.tar.gz
    dest: /project/udaapp/artifact.tar.gz
  register: copy_out

- name: extract artifact
  become: yes
  shell: |
    cd /project/udaapp
    unzip /project/udaapp/artifact.tar.gz
    npm install
    pm2 stop default
    pm2 start npm -- start