---

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Create directory
  become: yes
  file:
    path: "/project/udaapp"
    state: directory

- name: Upload artifact
  copy:
    src: files/artifact.tar.gz
    dest: /project/udaapp/artifact.tar.gz

- name: extract artifact
  become: yes
  shell: |
    cd /project/udaapp/
    unzip /project/udaapp/artifact.tar.gz
    npm install
    pm2 stop default
    pm2 start npm -- start