---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes


- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Create directory
  file:
    path: /home/ubuntu/udaappdir
    state: directory

- name: Upload artifact
  copy:
    src: ~/project/.circleci/ansible/roles/deploy/files/dist.zip
    dest: /home/ubuntu/udaappdir

- name: extract artifact
  become: true
  shell: |
    cd /home/ubuntu/udaappdir
    unzip /home/ubuntu/udaappdir/dist.zip
    pm2 stop default
    pm2 start npm -- start
  environment:
    NODE_ENV: production
    ENVIRONMENT: production
    TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    TYPEORM_MIGRATIONS_DIR: /home/ubuntu/udaappdir/migrations
    TYPEORM_MIGRATIONS: /home/ubuntu/udaappdir/migrations/*.js
    TYPEORM_ENTITIES: /home/ubuntu/udaappdir/modules/domain/**/*.entity.js
    TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env','TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"