---

- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "remove dependencies that are no longer required"
  become: yes
  apt:
    autoremove: yes

- name: "install nodejs and npm"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install n"
  become: yes
  npm:
    name: n
    global: yes
    production: yes

- name: "install nodejs 13.8.0"
  become: yes
  shell: n 13.8.0

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Install unzip
  become: yes
  apt:
    name: unzip
    state: present

- name: Create directory
  become: yes
  file:
    path: "/home/ubuntu/udaapp"
    state: directory
    mode: 0644

- name: Upload artifact
  become: yes
  copy:
    src: ~/project/.circleci/ansible/roles/deploy/files/dist.zip
    dest: /home/ubuntu/udaapp
  register: copy_out

- name: extract artifact
  become: yes
  shell: |
    cd /home/ubuntu/udaapp
    unzip /home/ubuntu/udaapp/dist.zip
    npm install
    pm2 stop default
    pm2 start npm -- start
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    TYPEORM_MIGRATIONS_DIR:  "{{ lookup('env','TYPEORM_MIGRATIONS_DIR') }}" 
    TYPEORM_MIGRATIONS: "{{ lookup('env','TYPEORM_MIGRATIONS') }}" 
    TYPEORM_ENTITIES: "{{ lookup('env','TYPEORM_ENTITIES') }}" 
    TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env','TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"